# Generated by Django 3.1.3 on 2022-06-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='content',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='is_choice_correct',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
        migrations.RemoveField(
            model_name='question',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='grade_point',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='question'),
        ),
    ]
